label = "go"
name = "golang"

[[file]]
  destination = "README.md"
  template = "README.md"

[[file]]
  destination = "cmd/__PROJECT_NAME__/main.go"
  template = "main.go"

[[folder]]
  destination = "bin"
  template = ""

[[folder]]
  destination = "cmd/__PROJECT_NAME__"
  template = ""

[[folder]]
  destination = "pkg/__PROJECT_NAME__"
  template = ""

[[script]]
  name = "init_go.sh"
  type = "post"
  execNumber = 1
  runAsSudo = false
  args = ["__PROJECT_NAME__"]

[[script]]
  name = "init_git.sh"
  type = "post"
  execNumber = 2
  runAsSudo = false
  args = []
