label = "web"
name = "webapp"

[[file]]
  destination = ".gitignore"
  template = "gitignore"

[[file]]
  destination = ".prettierrc.json"
  template = "prettierrc.json"

[[file]]
  destination = "README.md"
  template = ""

[[file]]
  destination = "public/index.html"
  template = "template.html"

[[file]]
  destination = "src/css/index.css"
  template = "template.css"

[[file]]
  destination = "src/index.js"
  template = ""

[[folder]]
  destination = "public/"
  template = ""

[[folder]]
  destination = "src/css/"
  template = ""

[[script]]
  name = "init_js.sh"
  type = "post"
  execNumber = 1
  runAsSudo = false
  args = []

[[script]]
  name = "init_git.sh"
  type = "post"
  execNumber = 2
  runAsSudo = false
  args = []
