label = "cpp"
name = "c-plus-plus"

[[file]]
  destination = "CMakeLists.txt"
  template = "CMakeLists-cpp.txt"

[[file]]
  destination = "README.md"
  template = "README.md"

[[file]]
  destination = "src/main.cpp"
  template = "main.cpp"

[[folder]]
  destination = ".vscode"
  template = "vscode-cpp"

[[folder]]
  destination = "build/debug/bin"
  template = ""

[[folder]]
  destination = "build/release/bin"
  template = ""

[[folder]]
  destination = "include"
  template = ""

[[folder]]
  destination = "src"
  template = ""

[[folder]]
  destination = "test"
  template = ""

[[script]]
  name = "init_git.sh"
  type = "post"
  execNumber = 1
  runAsSudo = false
  args = []
