# Don't print a new line at the start of the prompt
add_newline = true

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"


[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "
