#!/usr/bin/env sh

# Downloading a file via Aria2c
# @param $1 - destination
# @param $2 - url to download
# Check parameter
if [ ! -n "$1" ]; then
    echo "Error: Missing parameter"
    echo "Syntax: ytdl <url> ..."
    return 1
fi

youtube-dl -x --audio-quality 0 -i -o "%(title)s.%(ext)s" "$@"
